#cloud-config
apt_proxy: http://172.16.16.1:8000/
http_proxy: http://172.16.16.1:8000/

_foo: &SSH_KEY "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDRvvtm36t+RRYeG2BJN+ujWy2r5xFASgPFFYyQ85X7Guq4g/6wl94Z0f2WmxkUGSEpvsbGIpevcu2zIeUVnXt3noNlY1mKl4G9akNRFgw2P+1J5E2113l2UE90P344S4+rbNw4N+ZcMiHss/FT3iXYg6r6RCVHZoI7a4SIRdaABEUjyA6laF+5HhEQv7rz13+J17IOjLLBfby9xhRy9onjOsSHxKRVssdy4gTm91A3c9SRjh/ych3A6452CPiUAFbpnamICxybvMD/G6WMBQ0PYsSe7sWqwAbGU6g6TP1VWqs/9gPUVRv5daPE3Lv60onNHiQ27sUAC/4O59psSJJn jjo@sapito"

groups:
  - umcloud
users:
  - name: ubuntu
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [penasco-andres, "EDITAR_LP"]
    lock_passwd: true

  - name: umcloud
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    ssh-authorized-keys:
      - *SSH_KEY
    ssh-import-id: [penasco-andres, "EDITAR_LP"]
    primary-group: umcloud
    lock_passwd: true

apt_update: true

packages:
  - apache2-mpm-prefork
  - php5
  - php5-mysql
  - libapache2-mod-php5
  - curl
  - postfix
  - mlocate
  - unzip
  - php5-gd
  - libssh2-php


_foo: &DEPLOY_SH |
  #!/bin/bash
  #Descargar wp-config  
  cd /tmp
  wget http://wordpress.org/latest.tar.gz
  tar -xvzf latest.tar.gz
  cd /tmp/wordpress/
  cp wp-config-sample.php wp-config.php
  #Setear valores base de datos
  sed -i.bak 's/database_name_here/wordpress/g' wp-config.php
  sed -i.bak 's/username_here/wordpress/g' wp-config.php
  sed -i.bak 's/password_here/passwd/g' wp-config.php
  sed -i.bak 's/localhost/EDITAR_ENV-EDITAR_USUARIO-db.node.cloud.um.edu.ar/g' wp-config.php

  rsync -avP /tmp/wordpress/ /var/www/html/
  chown demo:www-data -R *
  mkdir /var/www/html/wp-content/uploads
  chown -R :www-data /var/www/html/wp-content/uploads


  #Descargamos consul
  cd /tmp
  wget http://192.168.3.251/consul/0.6.4/consul_0.6.4_linux_amd64.zip
  unzip *.zip
  cp consul /usr/local/sbin
  #creamos users dirs para consul
  useradd -d /var/consul -m consul
  mkdir -p /etc/consul.d
  # Mostramos resultado
  my_ip=$(ip r get 1 | sed -nr 's/.*src (\S+).*/\1/p')
  echo "*** INFO: READY, browse:"
  echo "    http://${my_ip?}/php-mysql"
  echo "*** INFO: END $0 $*"
  sleep 20
  exit 0



_foo: &CONSUL_CONF |
  {
    "server": false,
    "datacenter": "um-01",
    "data_dir": "/var/consul",
    "encrypt": "GIMbRTkH/rLwqjOWrMzrcw==",
    "log_level": "INFO",
    "domain": "cloud.um.edu.ar",
    "enable_syslog": true,
    "start_join": ["192.168.3.130"]
  }

_foo: &CONSUL_SERVICE |
  {
    "service":
      {
        "name": "web",
        "tags": ["apache"],
        "port": 80
      }
  }

_foo: &CONSUL_INIT |
  #! /bin/sh
  ### BEGIN INIT INFO
  # Provides:          consul
  # Required-Start:    $syslog $time $remote_fs
  # Required-Stop:     $syslog $time $remote_fs
  # Default-Start:     2 3 4 5
  # Default-Stop:      0 1 6
  # Short-Description: Services/nodes/kv discovery and storage
  # Description:       Debian init script for the consul agent
  ### END INIT INFO
  #
  # Author:            Diego Navarro <navarrow@gmail.com>
  #

  PATH=/bin:/usr/bin:/sbin:/usr/sbin
  DAEMON=/usr/local/sbin/consul
  PIDFILE=/var/run/consul

  test -x $DAEMON || exit 0

  . /lib/lsb/init-functions

  case "$1" in
    start)
          log_daemon_msg "Starting consul agent" "consul"
          start_daemon -p $PIDFILE $DAEMON agent -config-dir /etc/consul.d -client 0.0.0.0
          log_end_msg $?
      ;;
    stop)
          log_daemon_msg "Stoping consul agent" "consul"
          killproc -p $PIDFILE $DAEMON
          log_end_msg $?
      ;;
    force-reload|restart)
      $0 stop
      $0 start
      ;;
    status)
      status_of_proc -p $PIDFILE $DAEMON consul && exit 0 || exit $?
      ;;
    *)
      echo "Usage: /etc/init.d/consul {start|stop|restart|force-reload|status}"
      exit 1
      ;;
  esac
  exit 0
 
 
_foo: &CONFIG_APACHE_SH |
  #!/bin/bash
  METADATA=http://169.254.169.254/latest/meta-data/
  public_hostname=$(curl -s $METADATA/public-hostname)
  public_hostname=wp-apenasco.node.cloud.um.edu.ar
  public_ipv4=$(curl -s $METADATA/public-ipv4)
  local_ipv4=$(curl -s $METADATA/local-ipv4)
  # jjo: add .conf (required by more recent apache-s)
  cat > /etc/apache2/sites-available/wordpress.conf <<EOF
  <VirtualHost *:80>
      UseCanonicalName off
      Options All
      ServerAdmin webmaster@localhost
      ServerName $public_hostname
      ServerAlias $local_ipv4
      VirtualDocumentRoot /var/www/html
      RewriteEngine on
      RewriteRule ^/wp-uploads/(.*)$ /var/www/wp-uploads/%{HTTP_HOST}/\$1
      ErrorLog \${APACHE_LOG_DIR}/wordpress-error.log
      LogLevel warn
      CustomLog \${APACHE_LOG_DIR}/wordpress-access.log combined
  </VirtualHost>
  EOF
  a2enmod rewrite vhost_alias
  #a2dissite 000-default
  rm /var/www/html/index.html
  a2ensite wordpress
  service apache2 restart


_foo: &CONFIG_POSTFIX_SH |
  #!/bin/bash
  METADATA=http://169.254.169.254/latest/meta-data/
  public_hostname=$(curl -s $METADATA/public-hostname)
  public_hostname=wp-apenasco.node.cloud.um.edu.ar
  postconf -e myhostname=$public_hostname
  postconf -e mydestination=$public_hostname,localhost
  echo $public_hostname > /etc/mailname


write_files:
  - content: *DEPLOY_SH
    path: /usr/local/src/deploy.sh
    permissions: '0755'
  - content: *CONSUL_CONF
    path: /etc/consul.d/client.json
    permissions: '0644'
  - content: *CONSUL_SERVICE
    path: /etc/consul.d/wp.json
    permissions: '0644'
  - content: *CONSUL_INIT
    path: /etc/init.d/consul
    permissions: '0755'
  - content: *CONFIG_APACHE_SH
    path: /usr/local/src/config_apache.sh
    permissions: '0755'
  - content: *CONFIG_POSTFIX_SH
    path: /usr/local/src/config_postfix.sh
    permissions: '0755'


runcmd:
 - [ /usr/local/src/config_apache.sh ]
 - [ /usr/local/src/config_postfix.sh ]
 - [ /usr/local/src/deploy.sh ]
 - [ update-rc.d, consul, defaults ]
 - [ service, consul, start ]
 - [ service, apache2, restart ]
 - [ service, postfix, reload ]
 - [ /tmp/config_mysql.sh ]
